---

train:
  # Single training setting
  agent: "ImageNetAgent"
  device: "cuda"
  log_dir: "run"
  exp_name: "darknet53"
  n_epochs: 100
  interval: 20
  resume: false
  mode: "single"

dataset:
  size: 224
  train:
    root: "/home/advattack/imagenet_ssd/ILSVRC2012/train"
  valid:
    root: "/home/advattack/imagenet_ssd/ILSVRC2012/val"

dataloader:
  batch_size: 256
  num_workers: 8

model:
  name: "Darknet53"
  in_channels: 3
  num_classes: 1000

optimizer:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  warmup_epochs: 3
