---

train:
  agent: "ImageNetAgent"
  log_dir: "run"
  exp_name: "darknet53_dist"
  n_epochs: 100
  interval: 20
  resume: false
  # Distributed training setting
  mode: "parallel"
  master_addr: "localhost"
  master_port: "11000"
  gpus: [2, 3]

dataset:
  size: 224
  train:
    root: "/home/johnnylord/disk/ILSVRC2012/train"
  valid:
    root: "/home/johnnylord/disk/ILSVRC2012/val"

dataloader:
  batch_size: 64
  num_workers: 8

model:
  name: "Darknet53"
  kwargs:
    in_channels: 3
    num_classes: 1000

optimizer:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

# MultiStepLR Scheduler
scheduler:
  milestones: [10, 30, 60, 80]
  gamma: 0.1
