---

train:
  # Single training setting
  agent: "ImageNetAgent"
  device: "cuda:2"
  log_dir: "run"
  exp_name: "resnet18"
  n_epochs: 100
  interval: 20
  resume: false
  mode: "single"

dataset:
  size: 224
  train:
    root: "/home/advattack/imagenet/ILSVRC2012/train"
  valid:
    root: "/home/advattack/imagenet/ILSVRC2012/val"

dataloader:
  batch_size: 64
  num_workers: 4

optimizer:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  warmup_epochs: 5
