---

train:
  agent: "ImageNetAgent"
  log_dir: "run"
  exp_name: "resnet18_dist"
  n_epochs: 100
  interval: 20
  resume: false
  # Distributed training setting
  mode: "parallel"
  master_addr: "localhost"
  master_port: "11000"
  gpus: [0]
  #gpus: [0, 1, 2, 3]

dataset:
  size: 224
  train:
    root: "/home/advattack/imagenet_ssd/ILSVRC2012/train"
  valid:
    root: "/home/advattack/imagenet_ssd/ILSVRC2012/val"

dataloader:
  batch_size: 512
  num_workers: 8

model:
  name: "resnet18"
  kwargs:
    pretrained: true

optimizer:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  step_size: 10
  gamma: 0.1
