---

train:
  agent: "ImageNetAgent"
  device: "cuda"
  log_dir: "run"
  exp_name: "resnet18"
  n_epochs: 100
  interval: 20
  resume: false
  mode: "single"

dataset:
  size: 224
  train:
    root: "/home/johnnylord/disk/ILSVRC2012/train"
  valid:
    root: "/home/johnnylord/disk/ILSVRC2012/val"

dataloader:
  batch_size: 64
  num_workers: 8

model:
  name: "resnet18"
  kwargs:
    pretrained: true

# SGD Optimizer
optimizer:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

# MultiStepLR Scheduler
scheduler:
  milestones: [10, 30. 60. 80]
  gamma: 0.1

