---

train:
  agent: "ImageNetAgent"
  log_dir: "run"
  exp_name: "resnet18_dist"
  n_epochs: 100
  interval: 20
  resume: false
  # Distributed training setting
  mode: "parallel"
  master_addr: "localhost"
  master_port: "11000"
  gpus: [2]

dataset:
  size: 224
  ratio: 0.1
  train:
    root: "/home/johnnylord/disk/ILSVRC/Data/CLS-LOC/train"
  test:
    img_dir: "/home/johnnylord/disk/ILSVRC/Data/CLS-LOC/val"
    label_dir: "/home/johnnylord/disk/ILSVRC/Annotations/CLS-LOC/val"

dataloader:
  batch_size: 256
  num_workers: 4

optimizer:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  warmup_epochs: 5
