---

train:
  agent: "ImageNetAgent"
  log_dir: "run"
  exp_name: "resnet18_dist"
  n_epochs: 100
  interval: 20
  resume: false
  # Distributed training setting
  mode: "parallel"
  master_addr: "localhost"
  master_port: "11000"
  gpus: [0, 1, 2, 3]

dataset:
  root: "/home/johnnylord/datasets/ImageNet"
  size: 224
  ratio: 0.7

dataloader:
  batch_size: 64
  num_workers: 4

optim:
  lr: 0.001
